### DISCUSSION TITLE
Uncaught (in promise) RangeError: Offset is outside the bounds of the DataView

### DISCUSSION THREAD

**Discussion by tfabes** [jeffreylanters/react-unity-webgl#403] [Help Wanted!] [answered]
Hello! Thank you so much for this tool!

I have been able to get it working on localhost, but can't get it to work when hosted on AWS Amplify.

I'm getting an 'offset is outside the bounds of the dataview error' relating to the loader.js file.

I have seen someone have a similar issue (https://bytemeta.vip/repo/jeffreylanters/react-unity-webgl/issues/175) where the issue was that the data file was encoded as text / html.

I don't think this is the same issue I'm having, as in AWS I have set a custom header with the following:
  ```
customHeaders:
  - pattern: '*.wasm'
    headers:
      - key: Content-Type
        value: application/wasm
  - pattern: '*.js'
    headers:
      - key: Content-Type
        value: application/javascript
  - pattern: '*.data'
    headers:
      - key: Content-Type
        value: application/octet-stream
```
The point that it throws the error is at:
`var a=t.getUint32(r,!0);`
where t is the DataView.

I'm rather new to using React and would really appreciate any help anyone can offer on what I've missed out here! Been searching for a week or so without any luck on a solution.

Happy to DM a link to the webpage too if it's useful! Cheers!

<img width="447" alt="error1" src="https://user-images.githubusercontent.com/70435876/175961071-f123fbcf-6e55-4364-b71e-8532bdd6b166.png">
